FROM openjdk:17-oracle

WORKDIR /app

ADD "./target/matriculaudea-0.0.1-SNAPSHOT.jar" "app.jar"

ARG URL_DATABASE
ARG USERNAME_DB
ARG PASSWORD

ENV URL_DATABASE=${URL_DATABASE}
ENV USERNAME_DB=${USERNAME_DB}
ENV PASSWORD=${PASSWORD}

EXPOSE 8080

ENTRYPOINT ["java","-jar","app.jar"]